base_images:
  base:
    cluster: https://api.ci.openshift.org
    name: "4.4"
    namespace: ocp
    tag: base
build_root:
  image_stream_tag:
    cluster: https://api.ci.openshift.org
    name: release
    namespace: openshift
    tag: golang-1.12
canonical_go_repository: kubevirt.io/kubevirt
images:
- dockerfile_path: hack/ci/Dockerfile.ci
  from: base
  inputs:
    root:
      as:
      - builder
      paths: null
  to: kubevirt-test
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  cluster: https://api.ci.openshift.org
  name: "4.4"
  namespace: ocp
tests:
- artifact_dir: /go/src/kubevirt.io/kubevirt/_out/exported-artifacts
  as: e2e
  commands: |
    cd /go/src/kubevirt.io/kubevirt
    #./hack/ci/test.sh

    # TODO: this needs to be moved into kubevirt 'hack/ci/test.sh' again after the template has been merged,
    # putting it back in here for now to avoid fiddling with two repos in order to get it
    # working

    export PATH=$PATH:/usr/local/go/bin/

    export GIMME_GO_VERSION=1.12.8
    export GOPATH="/go"
    export GOBIN="/usr/bin"
    source /etc/profile.d/gimme.sh

    # we are using the provided openshift cluster, the external provider picks up the KUBECONFIG and
    # provides other values (like oc binary path) to the test configuration
    export KUBEVIRT_PROVIDER='external'

    # we are not running in privileged mode, therefore we need to run unnested (i.e. no docker in docker)
    export KUBEVIRT_RUN_UNNESTED=true

    # TODO: this could also be done in the Dockerfile.ci later on
    echo
    echo "--- building ---"
    echo
    bash -x ./hack/cluster-build.sh

    echo
    echo "--- calling cluster-up to prepare config and check whether cluster is reachable ---"
    echo
    bash -x ./cluster-up/up.sh

    echo
    echo "--- deploying ---"
    echo
    bash -x ./hack/cluster-deploy.sh

    echo
    echo "--- testing ---"
    echo
    mkdir -p "$ARTIFACT_DIR"
    TESTS_TO_FOCUS=$(grep -E -o '\[crit\:high\]' tests/*_test.go | sort | uniq | sed -E 's/tests\/([a-z_]+)\.go\:.*/\1/' | tr '\n' '|' | sed 's/|$//')
    FUNC_TEST_ARGS='--ginkgo.noColor --ginkgo.focus='"$TESTS_TO_FOCUS"' --ginkgo.regexScansFilePath=true --junit-output='"$ARTIFACT_DIR"'/junit.functest.xml' \
        bash -x ./hack/functests.sh

  openshift_installer_custom_test_image:
    cluster_profile: gcp
    from: pipeline:kubevirt-test
    enable_nested_virt: true
    nested_virt_image: rhcos43-nested-virt
