base_images:
  base:
    name: "4.2"
    namespace: ocp
    tag: base
build_root:
  project_image:
    context_dir: hack/kubevirt-builder
    dockerfile_path: Dockerfile
canonical_go_repository: kubevirt.io/kubevirt
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.2"
  namespace: ocp